#!/bin/bash
#
#  usage: AllocHelper k
#
#  where k is the number of registers for the allocator
#  to target. If k is not specified, it defaults to 5.
#
#  Locations for the ILOC Simulator, the Register Allocator,
#  and the command that actually runs the code are specified
#  in the defined variables SIM, ALLOC, and RUN
#
BASEDIR=$(dirname "$0")
SIM=/clear/courses/comp412/students/lab2/sim
ALLOC=$BASEDIR/../build/412fealloc
RUN=$BASEDIR/AllocOne
DIR=$(pwd)
#
FLIST=$(ls *.i)
echo "Allocator/Simulator test run in: $DIR"
echo "-----"
#
for f in $(ls *.i); do
    $RUN $f $ALLOC ${1:-5} $SIM
    echo "-----"
done
#

