#!/bin/python3
import subprocess
import os

base_dir = os.path.dirname(os.path.realpath(__file__))
script_path = os.path.join(base_dir,"Formatter")
registers = [3,4,5,6,8,10]

for i in range(len(registers)):
    result = subprocess.check_output([script_path, str(registers[i])])
    split = result.split(b"\n")
    for j in range(len(split)-1):
        print(int(split[j]))
