#!/bin/python3
import subprocess
import os

def percent_improvement(first,second):
    return (first - second) / first

base_dir = os.path.dirname(os.path.realpath(__file__))
script_path = os.path.join(base_dir,"Formatter")
script2_path = os.path.join(base_dir,"Formatter2")
# Number of report scripts
cycles = [[],[]]

result = subprocess.check_output([script_path])
split = result.split(b"\n")
for j in range(len(split)-1):
    cycles[0].append(int(split[j]))

result = subprocess.check_output([script2_path])
split = result.split(b"\n")
for j in range(len(split)-1):
    cycles[1].append(int(split[j]))

print("|Number|Mine|Reference|Percent|")
print("|-")

for i in range(len(cycles[0])):
    print("|report%d.i|%d|%d|%.1f|" % ((i+1),cycles[0][i], cycles[1][i], ((cycles[0][i] - cycles[1][i]) / cycles[1][i]) * 100))


